name: Build and publish nuget packages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet tool restore
      

    - name: Publish Fun.Blazor
      run: |
        dotnet pack -c Release Fun.Blazor/Fun.Blazor.fsproj -o .
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate

    - name: Publish Fun.Blazor.Cli
      run: |
        dotnet pack -c Release Fun.Blazor.Cli/Fun.Blazor.Cli.fsproj -o .
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
