name: Deploy to GitHub Pages

on:
  push:
    branches:
    - master
  # release:
  #   types: [published]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build artifacts
      run: |
        dotnet tool restore
        dotnet fsi build.fsx -t GenerateDocs
        dotnet publish Fun.Blazor.Docs.Wasm/Fun.Blazor.Docs.Wasm.fsproj -c Release -o Fun.Blazor.Docs.Wasm.Release --nologo
    

    # changes the base-tag in index.html from '/' to 'Fun.Blazor' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to Fun.Blazor.Docs
      run: sed -i 's/<base href="\/"\/>/<base href="\/Fun.Blazor.Docs\/" \/>/g' Fun.Blazor.Docs.Wasm.Release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: Create 404.html
      run: cp Fun.Blazor.Docs.Wasm.Release/wwwroot/index.html Fun.Blazor.Docs.Wasm.Release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch Fun.Blazor.Docs.Wasm.Release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        token: ${{ secrets.GH_PAGES_PAT }}
        branch: gh-pages
        folder: Fun.Blazor.Docs.Wasm.Release/wwwroot
        repository-name: slaveOftime/Fun.Blazor.Docs